name: Go Check Formatting
description: Checks that the code is formatted with `goimports`
inputs:
  package:
    description: Package to format
    required: false
    default: .

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true
        cache: false
    - name: Install goimports
      shell: bash
      run: go install golang.org/x/tools/cmd/goimports@latest
    - name: Format
      working-directory: ${{ inputs.package }}
      shell: bash
      run: goimports -w .
    - name: Check if files changed
      working-directory: ${{ inputs.package }}
      shell: bash
      run: git diff --exit-code
