name: Test Release Go Binaries

on:
  release:
    types:
      - created
  push:
    branches:
      - master

jobs:
  test-release-go-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: ./release-go-binaries
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package: test/go-application
          goos: linux
          goarch: amd64
          ldflags: -X main.toGreet=World