name: Test Go Check Formatting

on:
  push:

jobs:
  test-go-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Formatting
        uses: ./go-check-formatting
        with:
          package: test/go-application
