name: Test Release Go Binaries

on:
  release:
    types:
      - created
  push:
    branches:
      - master

jobs:
  test-release-go-binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: ./release-go-binaries
        with:
          goos: linux
          goarch: amd64
          ldflags: "-X "main.toGreet=World"