name: Test Go Format

on:
  push:

jobs:
  test-go-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./go-format
        with:
          package: test/go-application
