name: Test Go Test

on:
  push:

jobs:
  test-go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests
        uses: ./go-test
        with:
          package: test/go-application
